title: Malick Ndiaye
description: >- 
  Le portfolio de Malick Ndiaye, ingénieur logiciel. Développé avec Jekyll, il me présente professionnellement et met en valeur mes compétences et projets.
domain: modern-malick.com
url: https://modern-malick.com
baseurl: ""

  