title: Malick Ndiaye
description: >-
  Portfolio de Malick Ndiaye, développeur Full-Stack spécialisé en applications web, mobile et windows. Je suis prêt à transformer vos défis en succés. Conçu avec Jekyll, ce portfolio offre une présentation professionnelle mettant en lumière mes compétences et mes projets. Vous y trouverez également la possibilité de me contacter pour toute collaboration potentielle.
domain: modern-malick.com
url: https://modern-malick.com/
permalink: pretty
excerpt_separator: <!-- end-excerpt -->